  - name: Download JRE archive.
    get_url:
      url: '{{jre_url}}'
      dest: /tmp/jre-{{jre_version}}-linux-x64.tar.gz
      headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

  - name: Create the JRE target directory.
    file:
      path: '{{jre_dir}}'
      state: directory
      recurse: yes

  - name: Uncompress the JRE archive.
    unarchive:
      copy: no
      src: /tmp/jre-{{jre_version}}-linux-x64.tar.gz
      dest: '{{jre_dir}}'
